Repository AICoE/log-anomaly-detector, pull requests merged in 2019-11, with the labels that each got.

#349 Fix minor typo in cli option
  app.py
Labels: approved, size/XS

#351 Adding singleton to ensure we only have a single session at all times.
  anomaly_detector/fact_store/api.py
Labels: approved, size/XS

#350 Adding mysql exporter for better visibility of too many threads in mysql
  openshift/databases/mysql-exporter.yaml
  openshift/metrics/grafana_dashboards/mysql-exporter-dashboard.json
Labels: approved, size/M, size/XXL

#354 Adding badges to show project status
  README.rst
Labels: approved, size/M

#358 Removed unused imports and unused code
  anomaly_detector/config.py
  anomaly_detector/core/job.py
  anomaly_detector/facade.py
  anomaly_detector/fact_store/api.py
  anomaly_detector/fact_store/app.py
  anomaly_detector/fact_store/model.py
  anomaly_detector/storage/local_storage.py
  anomaly_detector/storage/storage_attribute.py
  anomaly_detector/storage/storage_proxy.py
  anomaly_detector/storage/storage_sink.py
Labels: approved, size/M

#361 Adding better test case structure to unit tests
  tests/conftest.py
  tests/test_factstore.py
  tests/test_false_anomaly_check.py
  tests/test_pipeline_jobs.py
  tests/test_som.py
  tests/test_storage_catalog.py
  tests/test_storage_proxy.py
  tests/test_task_manager.py
  tests/test_valid_storage.py
  tests/test_validation_data.py
  tests/test_w2v.py
Labels: approved, size/L

#362 Adding markers to test cases
  tests/test_factstore.py
  tests/test_false_anomaly_check.py
  tests/test_pipeline_jobs.py
  tests/test_som.py
  tests/test_storage_catalog.py
  tests/test_storage_proxy.py
  tests/test_valid_storage.py
  tests/test_validation_data.py
  tests/test_w2v.py
Labels: approved, size/M

#363 Cleaning up w2v test removing print and replacing with logging
  tests/test_w2v.py
Labels: approved, size/XS

#365 Adding faster test runs
  .travis.yml
  Pipfile
  Pipfile.lock
  pytest.ini
  setup.py
Labels: approved, size/L

#366 update factstore to use sqlalchemy
  Pipfile
  Pipfile.lock
  anomaly_detector/fact_store/__init__.py
  anomaly_detector/fact_store/api.py
  anomaly_detector/fact_store/app.py
  anomaly_detector/fact_store/app/__init__.py
  anomaly_detector/fact_store/app/deploy_prod.py
  anomaly_detector/fact_store/app/imgs/design.jpg
  anomaly_detector/fact_store/app/models/__init__.py
  anomaly_detector/fact_store/app/models/controller.py
  anomaly_detector/fact_store/app/models/model.py
  anomaly_detector/fact_store/app/templates/index.html
  anomaly_detector/fact_store/app/views/api.py
  anomaly_detector/fact_store/app/views/index.py
  anomaly_detector/fact_store/model.py
  app.py
  tests/conftest.py
  tests/test_factstore.py
Labels: approved, size/XL
