Repository AICoE/log-anomaly-detector, pull requests merged in 2019-07, with the labels that each got.

#162 Removing unused code for loading data from storage
  anomaly_detector/adapters/som_model_adapter.py
  anomaly_detector/adapters/som_storage_adapter.py
  anomaly_detector/anomaly_detector_facade.py
  app.py
  tests/test_false_anomaly_check.py
Labels: PR-in-review, refactor

#169 Adding better handling of None value returned from Elasticsearch no log results causes crash
  anomaly_detector/adapters/som_storage_adapter.py
Labels: PR-in-review, bug

#174 Adding simple decorator utility to log latency of function
  anomaly_detector/adapters/som_model_adapter.py
  anomaly_detector/adapters/som_storage_adapter.py
  anomaly_detector/decorator/__init__.py
  anomaly_detector/decorator/utils.py
Labels: logging, performance

#180 adding gate section for zuul
  .zuul.yaml
Labels: approved

#176 [Plugin] Creating smarter system for queuing up tasks performed in training vs inference
  anomaly_detector/adapters/base_model_adapter.py
  anomaly_detector/adapters/som_model_adapter.py
  anomaly_detector/adapters/som_storage_adapter.py
  anomaly_detector/anomaly_detector_facade.py
  anomaly_detector/jobs/__init__.py
  anomaly_detector/jobs/tasks.py
  tests/test_false_anomaly_check.py
  tests/test_task_manager.py
  tests/test_validation_data.py
Labels: PR-in-review, approved, model-inference, model-training

#178 Added observability in anomaly detection code
  anomaly_detector/adapters/som_model_adapter.py
  anomaly_detector/anomaly_detector_facade.py
  anomaly_detector/jobs/tasks.py
Labels: PR-in-review, approved, metrics

#179 Ensure single instance of Task Queue exists in the lifetime of application.
  anomaly_detector/jobs/tasks.py
  tests/test_task_manager.py
Labels: PR-in-review, approved, refactor

#183 Return the smallest instead of the last distance
  anomaly_detector/model/sompy_model.py
Labels: approved, model-training

#184 Average score of anomaly predictions
  anomaly_detector/adapters/som_model_adapter.py
Labels: metrics

#185 Removing unused legacy code
  anomaly_detector/anomaly_detector.py
Labels: refactor
