Repository AICoE/log-anomaly-detector, pull requests merged in 2019-10, with the labels that each got.

#254 Always online exception handling
  anomaly_detector/anomaly_detector_facade.py
  anomaly_detector/exception/__init__.py
  anomaly_detector/exception/exceptions.py
  anomaly_detector/jobs/tasks.py
Labels: approved, size/M, size/S

#248 Adding Kafka sink
  Pipfile
  Pipfile.lock
  anomaly_detector/config.py
  anomaly_detector/jobs/tasks.py
  anomaly_detector/storage/__init__.py
  anomaly_detector/storage/kafka_sink.py
  config_files/.env_cmn_log_fmt_config_kafka.yaml
Labels: approved, size/L, size/M, storage

#255 cleaned up variables and provided better docs
  anomaly_detector/anomaly_detector_facade.py
Labels: approved, size/M

#256 removing unused packages and code
  anomaly_detector/adapters/som_model_adapter.py
  anomaly_detector/config.py
  anomaly_detector/events/__init__.py
  anomaly_detector/events/anomaly_event.py
  anomaly_detector/jobs/tasks.py
  anomaly_detector/storage/es_storage.py
  anomaly_detector/storage/local_directory_storage.py
  anomaly_detector/storage/local_storage.py
  anomaly_detector/types/__init__.py
  anomaly_detector/types/anomaly_status.py
Labels: approved, size/L

#249 Update factstore deployment template
  Makefile
  openshift/factstore.app.yaml
Labels: approved, size/M

#247 Updated documentation to include new styling for better UI
  docs/requirements.txt
  docs/source/changelog.rst
  docs/source/cli.rst
  docs/source/conf.py
  docs/source/goals.rst
  docs/source/index.rst
  docs/source/use_case.rst
Labels: approved, size/L, size/S

#250 Add elasticsearch deployment template
  Makefile
  openshift/lad-elasticsearch-deployment.yaml
Labels: approved, size/M

#257 Added updated logs on storage
  docs/source/architecture.rst
  docs/source/factstore.rst
  docs/source/index.rst
  docs/source/model.rst
  docs/source/storage.rst
Labels: approved, size/M, size/S

#258 Adding source sync to allow for getting and pushing data to different…
  anomaly_detector/adapters/feedback_strategy.py
  anomaly_detector/adapters/som_model_adapter.py
  anomaly_detector/config.py
  anomaly_detector/storage/kafka_sink.py
  anomaly_detector/storage/storage_sink.py
  anomaly_detector/storage/storage_source.py
  tests/test_false_anomaly_check.py
Labels: approved, size/M

#260 added ability to make som configurable
  anomaly_detector/config.py
  anomaly_detector/model/sompy_model.py
Labels: approved, size/S

#259 Adding opentracing to log_anomaly_detector
  Pipfile
  Pipfile.lock
  anomaly_detector/adapters/som_model_adapter.py
  anomaly_detector/adapters/som_storage_adapter.py
  anomaly_detector/anomaly_detector_facade.py
  anomaly_detector/jobs/tasks.py
  app.py
  docs/source/cli.rst
Labels: approved, size/L

#263 added local outlier factor notebook experiment
  Notebooks/experiment/LAD_local_outlier_factor.ipynb
Labels: approved, size/XXL

#262 Change default config vals for SOMPY so that it is recognized as an int
  anomaly_detector/config.py
Labels: approved, size/XS

#267 Fixing documentation for LAD Core
  Makefile
  anomaly_detector/README.md
  model_extension_specification
  openshift/README.rst
  openshift/aiops_factstore.deployment.yaml
  openshift/aiops_lad_core.buildconfig.yaml
  openshift/aiops_lad_core.configmap.deployment.yaml
  openshift/aiops_lad_core.elasticsearch.storage.yaml
  openshift/aiops_lad_core.env_var_config.deployment.yaml
  openshift/aiops_lad_core.example.configuration.yaml
  openshift/aiops_lad_core.k8s.service.yaml
  openshift/aiops_lad_core.minimal.deployment.yaml
  openshift/aiops_lad_core.ml.job.yaml
Labels: approved, size/M, size/S

#265 Create log-anomaly-detector-minishift.yaml
  openshift/log-anomaly-detector-minishift.yaml
Labels: approved, size/L

#273 Adding better structure to api for training models
  anomaly_detector/anomaly_detector_facade.py
  anomaly_detector/config.py
  anomaly_detector/jobs/__init__.py
  anomaly_detector/jobs/core.py
  tests/test_false_anomaly_check.py
  tests/test_som.py
  tests/test_task_manager.py
  tests/test_valid_storage.py
  tests/test_validation_data.py
  tests/test_w2v.py
Labels: approved, size/L, size/M

#261 Fix incorrect index when checking for empty queries
  anomaly_detector/storage/es_storage.py
Labels: approved, size/XS

#275 Add templates for elastalert deployment
  openshift/aiops_factstore.deployment.yaml
  openshift/elastalert/lad-elastalert-buildconfig.yaml
  openshift/elastalert/lad-elastalert-deployment.yaml
Labels: approved, size/L

#266 Adding new api for storage and catalog to select storage
  anomaly_detector/adapters/som_storage_adapter.py
  anomaly_detector/config.py
  anomaly_detector/storage/__init__.py
  anomaly_detector/storage/es_storage.py
  anomaly_detector/storage/kafka_storage.py
  anomaly_detector/storage/local_directory_storage.py
  anomaly_detector/storage/local_storage.py
  anomaly_detector/storage/storage.py
  anomaly_detector/storage/storage_catalog.py
  anomaly_detector/storage/storage_proxy.py
  anomaly_detector/storage/storage_sink.py
  anomaly_detector/storage/storage_source.py
  config_files/.env_cmn_log_fmt_config.yaml
  config_files/.env_config.yaml
  config_files/.env_local_dir.yaml
  tests/test_storage_catalog.py
Labels: approved, size/L

#279 Fix
  anomaly_detector/storage/storage_catalog.py
Labels: approved, size/XS

#283 Update Makefile
  Makefile
Labels: approved, size/M

#288 Removing legacy code
  anomaly_detector/config.py
  anomaly_detector/jobs/core.py
Labels: approved, size/S

#290 update setup.py for not utf-8 system
  setup.py
Labels: approved, size/XS

#291 Added kebechet support
  .thoth.yaml
Labels: approved, size/S

#285 Fixing storage documentation
  config_files/minishift-demo/.env_config_es_local.yaml
  docs/source/_static/logo.svg
  docs/source/_static/logo_docs.png
  docs/source/anomaly_detector.adapters.rst
  docs/source/anomaly_detector.decorator.rst
  docs/source/anomaly_detector.events.rst
  docs/source/anomaly_detector.exception.rst
  docs/source/anomaly_detector.fact_store.rst
  docs/source/anomaly_detector.jobs.rst
  docs/source/anomaly_detector.model.rst
  docs/source/anomaly_detector.rst
  docs/source/anomaly_detector.storage.rst
  docs/source/anomaly_detector.types.rst
  docs/source/api_reference.rst
  docs/source/conf.py
  docs/source/configinfo.rst
  docs/source/modules.rst
  docs/source/storage.rst
  imgs/storage-example.png
Labels: approved, size/L, size/S

#278 allowing for configurable initialization parameter for SOM model
  anomaly_detector/config.py
  anomaly_detector/model/sompy_model.py
Labels: approved, size/XS

#293 Adding update to pypi
  Pipfile.lock
  setup.py
Labels: approved, size/M, size/S

#294 Update oc deployment templates for new config
  Makefile
  openshift/aiops_factstore.deployment.yaml
  openshift/log-anomaly-detector-minishift.yaml
  openshift/metrics/prometheus.yaml
Labels: approved, size/L, size/S

#295 Adding Grafana Dashboard
  openshift/metrics/grafana_dashboards/log_anomaly_detector_dashboard.json
Labels: approved, size/XXL

#300 Update log_anomaly_detector_dashboard.json
  openshift/metrics/grafana_dashboards/log_anomaly_detector_dashboard.json
Labels: approved, size/S

#307 Add deployment template for grafana
  Makefile
  openshift/metrics/grafana.yaml
  openshift/metrics/setup_grafana.sh
Labels: approved, size/L

#296 Update release s2i
  README.rst
  scripts/build-s2i-push-quay.sh
Labels: approved, developer-productivity, size/S

#305 Adding ability to monitor when we fail to write feedback to db.
  anomaly_detector/fact_store/app.py
Labels: approved, size/XS

#309 updated Makefile to point to new demo repo & template api ver
  Makefile
  openshift/aiops_lad_core.elasticsearch.storage.yaml
Labels: approved, size/XS

#310 [WIP]add anisble playbook to deploy prometheus
  playbooks/lad-prometheus.yaml
  playbooks/templates/prometheus-openshift-objects.yaml
  playbooks/vars/common-vars.yaml
  playbooks/vars/prometheus-vars.yaml
Labels: approved, do-not-merge/work-in-progress, size/L

#308 Adding encoder class for log anomaly detector.
  anomaly_detector/jobs/core.py
Labels: approved, size/M

#287 [WIP] Adding fix to storage
  anomaly_detector/storage/es_storage.py
Labels: approved, do-not-merge/work-in-progress, size/XS

#312 Adding better proper templates
  openshift/aiops_factstore.deployment.yaml
  openshift/aiops_lad_core.example.configuration.yaml
  openshift/aiops_lad_core.minimal.deployment.yaml
  openshift/databases/mysql-persistant.json
Labels: approved, size/L, size/M, size/XL, size/XXL

#318 Update es_storage.py
  anomaly_detector/storage/es_storage.py
Labels: approved, size/XS

#319 added es version config and separation logic to es_storage
  anomaly_detector/config.py
  anomaly_detector/storage/es_storage.py
  openshift/log-anomaly-detector-minishift.yaml
Labels: approved, do-not-merge/needs-rebase, size/XS

#322 added elastalert flag to allow us to turn off notifications via config
  anomaly_detector/adapters/som_model_adapter.py
  anomaly_detector/config.py
Labels: approved, do-not-merge/needs-rebase, size/L, size/XS

#323 adding transaction id to batch of logs for inference.
  anomaly_detector/adapters/som_model_adapter.py
Labels: approved, do-not-merge/needs-rebase, size/XS

#324 Added flask metrics to allow us to see fact_store health via grafana
  Pipfile
  Pipfile.lock
  anomaly_detector/fact_store/api.py
  anomaly_detector/fact_store/app.py
  setup.py
  tests/test_factstore.py
Labels: approved, do-not-merge/needs-rebase, size/L

#325 Add playbook for grafana deployment
  playbooks/lad-grafana.yaml
  playbooks/templates/grafana-dashboards/log_anomaly_detector_dashboard.json
  playbooks/templates/grafana-openshift-objects.yaml
  playbooks/vars/grafana-vars.yaml
Labels: approved, size/XXL

#321 Adding custom log formatting
  anomaly_detector/config.py
  anomaly_detector/storage/es_storage.py
  anomaly_detector/storage/storage.py
  docs/source/configinfo.rst
Labels: approved, do-not-merge/needs-rebase, size/M, size/S

#327 Add playbook to deploy elasticsearch
  playbooks/lad-elasticsearch.yaml
  playbooks/templates/elasticsearch-openshift-objects.yaml
  playbooks/vars/elasticsearch-vars.yaml
Labels: approved, do-not-merge/needs-rebase, size/M

#330 Add playbook for factstore deployment
  playbooks/lad-factstore.yaml
  playbooks/templates/factstore-openshift-objects.yaml
  playbooks/vars/factstore-vars.yaml
Labels: approved, do-not-merge/needs-rebase, size/L

#328 Adding stdout console
  anomaly_detector/adapters/som_model_adapter.py
  anomaly_detector/storage/stdout_sink.py
  anomaly_detector/storage/storage_catalog.py
  anomaly_detector/storage/storage_sink.py
  config_files/.env_cmn_log_fmt_config.yaml
  docs/source/storage.rst
Labels: approved, do-not-merge/needs-rebase, size/M

#329 parameterize git info in tmpl & yaml-ify mysql
  openshift/databases/mysql-persistant.json
  openshift/databases/mysql-persistent.yaml
  openshift/log-anomaly-detector-minishift.yaml
Labels: approved, size/L

#332 Updated dashboard json file
  openshift/metrics/grafana_dashboards/log_anomaly_detector_dashboard.json
Labels: approved, size/XL

#331 Add playbook to deploy the log-anomaly-detector application
  playbooks/log-anomaly-detector.yaml
  playbooks/templates/lad-openshift-objects.yaml
  playbooks/vars/lad-vars.yaml
Labels: approved, size/L

#333 Moving tags higher up
  anomaly_detector/adapters/som_model_adapter.py
Labels: approved, size/XS

#338 Update .zuul.yaml
  .zuul.yaml
Labels: approved, size/XS

#337 Adding ability to search logs in elasticsearch
  openshift/aiops_lad_core.kibana.datatools.yaml
Labels: approved, size/M

#339 Update lad-grafana.yaml
  playbooks/lad-grafana.yaml
Labels: approved, size/XS

#340 Adjust custom rules for Storage Proxy so you can not pass .source or .sink
  anomaly_detector/config.py
  anomaly_detector/storage/storage_catalog.py
  anomaly_detector/storage/storage_proxy.py
  docs/source/storage.rst
  tests/test_false_anomaly_check.py
  tests/test_som.py
  tests/test_storage_catalog.py
  tests/test_storage_proxy.py
  tests/test_task_manager.py
  tests/test_valid_storage.py
  tests/test_validation_data.py
  tests/test_w2v.py
Labels: approved, size/L, size/M

#341 Adding storage docs
  docs/source/storage.rst
Labels: approved, size/S

#342 Add ability to track namespace where prediction originated.
  anomaly_detector/adapters/som_model_adapter.py
  anomaly_detector/config.py
Labels: approved, size/XS

#316 added e2e tests
  Pipfile
  Pipfile.lock
  setup.cfg
  tests/e2e/Makefile
  tests/e2e/__init__.py
  tests/e2e/configs/cleanup.yaml
  tests/e2e/configs/fulltest.yaml
  tests/e2e/conftest.py
  tests/e2e/pytest.ini
  tests/e2e/test_openshift_deployments.py
  tests/e2e/util.py
Labels: approved, size/XXL, test-case

#346 Added better docs and more clear information about parameters passed.
  anomaly_detector/__init__.py
  anomaly_detector/facade.py
  app.py
Labels: approved, size/M

#347 Refactoring code base to utilize better encapsulation
  anomaly_detector/core/__init__.py
  anomaly_detector/core/detector_pipeline.py
  anomaly_detector/core/encoder.py
  anomaly_detector/core/job.py
  anomaly_detector/facade.py
  anomaly_detector/jobs/__init__.py
  anomaly_detector/jobs/core.py
  anomaly_detector/model/w2v_model.py
  tests/test_false_anomaly_check.py
  tests/test_som.py
  tests/test_task_manager.py
  tests/test_valid_storage.py
  tests/test_validation_data.py
  tests/test_w2v.py
Labels: approved, size/XL
