Repository AICoE/log-anomaly-detector, pull requests merged in 2019-06, with the labels that each got.

#153 Refactoring api into model adaptor and storage adaptor classes
  Pipfile.lock
  anomaly_detector/adapters/__init__.py
  anomaly_detector/adapters/base_model_adapter.py
  anomaly_detector/adapters/base_storage_adapter.py
  anomaly_detector/adapters/som_model_adapter.py
  anomaly_detector/adapters/som_storage_adapter.py
  anomaly_detector/anomaly_detector_facade.py
  app.py
  tests/test_false_anomaly_check.py
  tests/test_validation_data.py
Labels: architecture design decision, refactor

#149 Added a "Notebooks" directory
  Notebooks/SOM_retrain_notebook/README.md
  Notebooks/SOM_retrain_notebook/SOM.py
  Notebooks/SOM_retrain_notebook/SOM_UserFeedbackPOC.ipynb
  Notebooks/SOM_retrain_notebook/map_1.gif
  Notebooks/SOM_retrain_notebook/map_2.gif
  Notebooks/SOM_retrain_notebook/map_3.gif
  Notebooks/SOM_retrain_notebook/map_4.gif
Labels: architecture design decision

#155 Adding configurable parameters to LAD so we can configure prometheus …
  app.py
Labels: PR-in-review, bug

#157 Setting up custom strategy for feedback. Provide a pluggable way for drop in replacements for feedback
  anomaly_detector/adapters/feedback_strategy.py
  anomaly_detector/adapters/som_model_adapter.py
  anomaly_detector/adapters/som_storage_adapter.py
  anomaly_detector/anomaly_detector_facade.py
  app.py
  tests/test_false_anomaly_check.py
Labels: PR-in-review, refactor

#166 Adding inmemory default for sqlite for cross platform compatibility
  anomaly_detector/fact_store/fact_store_api.py
Labels: PR-in-review, bug

#170 removing _stdin function as it is unused.
  anomaly_detector/storage/local_storage.py
Labels: PR-in-review, refactor, storage

#171 Adding better handling of storage attributes
  anomaly_detector/adapters/som_storage_adapter.py
  anomaly_detector/storage/es_storage.py
  anomaly_detector/storage/local_storage.py
  anomaly_detector/storage/storage.py
  anomaly_detector/storage/storage_attribute.py
Labels: PR-in-review, refactor, storage

#172 Adding delegation to storage_adapter to proxy configs
  anomaly_detector/adapters/som_model_adapter.py
  anomaly_detector/adapters/som_storage_adapter.py
Labels: PR-in-review, architecture design decision, storage

#175 additional exception classes
  anomaly_detector/exception/exceptions.py
Labels: exception-handling, logging
