Repository AICoE/log-anomaly-detector, pull requests merged in 2019-09, with the labels that each got.

#212 Adding better handling of encoding
  .env_cmn_log_fmt_config_feedback.yaml
  anomaly_detector/adapters/som_model_adapter.py
  run-lad-job.sh
  run-web-ui.sh
Labels: enhancement

#215 Documenting more details on how someone can join us and contribute
  CONTRIBUTING.rst
  README.rst
  _config.yml
  docs/source/index.rst
  imgs/components.png
Labels: approved, documentation, size/L, size/XL, size/XS, size/XXL

#218 Adding better structure to the project
  .stickler.yml
  LICENSE.txt
  config_files/.env_cmn_log_fmt_config.yaml
  config_files/.env_cmn_log_fmt_config_feedback.yaml
  config_files/.env_config.yaml
  config_files/.test_env_config.yaml
  config_files/.test_env_config_fact_store.yaml
  run-lad-job.sh
  scripts/run-lad-job.sh
  scripts/run-web-ui.sh
  tests/test_false_anomaly_check.py
  tests/test_task_manager.py
  tests/test_validation_data.py
Labels: approved, size/L

#217 Adding contributions guideline document
  CONTRIBUTING_GUIDELINE.rst
Labels: approved, size/M

#216 added specification for model extensions
  imgs/figure1.png
  model_extension_specification
  specifications/model_extensions.rst
Labels: approved, size/M

#221 Adding docs on configuration and hyperparameters for LAD
  docs/source/configinfo.rst
  docs/source/factstore.rst
Labels: approved, size/L

#228 Packaging update
  setup.py
Labels: size/L, size/XS

#225 Cleaning up imports to have a cleaner api
  anomaly_detector/adapters/__init__.py
  anomaly_detector/adapters/som_model_adapter.py
  anomaly_detector/adapters/som_storage_adapter.py
  anomaly_detector/events/__init__.py
  anomaly_detector/events/anomaly_event.py
  anomaly_detector/exception/__init__.py
  anomaly_detector/exception/exceptions.py
  anomaly_detector/jobs/__init__.py
  anomaly_detector/model/__init__.py
  anomaly_detector/model/base_model.py
  anomaly_detector/model/model_exception.py
  anomaly_detector/model/som_model.py
  anomaly_detector/model/sompy_model.py
  anomaly_detector/model/w2v_model.py
  anomaly_detector/storage/__init__.py
  anomaly_detector/storage/es_storage.py
  anomaly_detector/storage/local_storage.py
  anomaly_detector/storage/storage.py
  anomaly_detector/storage/storage_attribute.py
  anomaly_detector/types/__init__.py
  tests/test_false_anomaly_check.py
  tests/test_task_manager.py
  tests/test_validation_data.py
Labels: size/L

#230 Add preliminary unit tests for SOM
  tests/test_som.py
Labels: approved, size/M

#227 Adding LAD feature to process logs from a directory instead of single file.
  anomaly_detector/adapters/som_storage_adapter.py
  anomaly_detector/storage/__init__.py
  anomaly_detector/storage/local_directory_storage.py
  config_files/.env_local_dir.yaml
  tests/test_valid_storage.py
  validation_data/test_sample_input/application_1445182159119_0001/orders-500.log
  validation_data/test_sample_input/application_1445182159119_0001/sample_ecommerce-1.log
  validation_data/test_sample_input/application_1445182159119_0001/sample_ecommerce-2.log
  validation_data/test_sample_input/application_1445182159119_0001/sample_ecommerce-3.log
  validation_data/test_sample_input/application_1445182159119_0001/sample_ecommerce-4.log
  validation_data/test_sample_input/application_1445182159119_0001/sample_ecommerce-5.log
  validation_data/test_sample_input/application_1445182159119_0001/sample_ecommerce.log
  validation_data/test_sample_input/application_1445182159119_0002/sample_ecommerce-1.log
  validation_data/test_sample_input/application_1445182159119_0002/sample_ecommerce-2.log
  validation_data/test_sample_input/application_1445182159119_0002/sample_ecommerce-3.log
  validation_data/test_sample_input/application_1445182159119_0002/sample_ecommerce-4.log
  validation_data/test_sample_input/application_1445182159119_0002/sample_ecommerce-5.log
  validation_data/test_sample_input/application_1445182159119_0002/sample_ecommerce.log
  validation_data/test_sample_input/application_1445182159119_0003/sample_ecommerce-1.log
  validation_data/test_sample_input/application_1445182159119_0003/sample_ecommerce-2.log
  validation_data/test_sample_input/application_1445182159119_0003/sample_ecommerce-3.log
  validation_data/test_sample_input/application_1445182159119_0003/sample_ecommerce-4.log
  validation_data/test_sample_input/application_1445182159119_0003/sample_ecommerce-5.log
  validation_data/test_sample_input/application_1445182159119_0003/sample_ecommerce.log
  validation_data/test_sample_input/application_1445182159119_0004/sample_ecommerce-1.log
  validation_data/test_sample_input/application_1445182159119_0004/sample_ecommerce-2.log
  validation_data/test_sample_input/application_1445182159119_0004/sample_ecommerce-3.log
  validation_data/test_sample_input/application_1445182159119_0004/sample_ecommerce-4.log
  validation_data/test_sample_input/application_1445182159119_0004/sample_ecommerce-5.log
  validation_data/test_sample_input/application_1445182159119_0004/sample_ecommerce.log
  validation_data/test_sample_input/application_1445182159119_0005/sample_ecommerce-1.log
  validation_data/test_sample_input/application_1445182159119_0005/sample_ecommerce-2.log
  validation_data/test_sample_input/application_1445182159119_0005/sample_ecommerce-3.log
  validation_data/test_sample_input/application_1445182159119_0005/sample_ecommerce-4.log
  validation_data/test_sample_input/application_1445182159119_0005/sample_ecommerce-5.log
  validation_data/test_sample_input/application_1445182159119_0005/sample_ecommerce.log
Labels: approved, size/L, size/XL, size/XXL, storage

#232 Adding custom fields to w2v model for more control on cbow vs skip-grams
  anomaly_detector/adapters/som_model_adapter.py
  anomaly_detector/config.py
  anomaly_detector/model/base_model.py
  anomaly_detector/model/sompy_model.py
  anomaly_detector/model/w2v_model.py
  docs/source/configinfo.rst
Labels: approved, size/M

#233 Added unit tests for w2v model
  config_files/.env_config.yaml
  tests/test_w2v.py
Labels: approved, size/M

#234 Updating templates and configmaps to support deploying multiple applications in same namespace
  openshift/factstore.app.yaml
  openshift/log-anomaly-detector.app.yaml
  openshift/sample.config.yaml
Labels: approved, size/L

#239 Update lad-build-cfg.yaml
  openshift/lad-build-cfg.yaml
Labels: approved, size/M

#242 allowing configurations and anomaly facade to be imported with *
  anomaly_detector/__init__.py
  anomaly_detector/anomaly_detector_facade.py
Labels: approved, size/XS

#241 Adding better api docs
  docs/requirements.txt
  docs/source/anomaly_detector.adapters.rst
  docs/source/anomaly_detector.decorator.rst
  docs/source/anomaly_detector.events.rst
  docs/source/anomaly_detector.exception.rst
  docs/source/anomaly_detector.fact_store.rst
  docs/source/anomaly_detector.jobs.rst
  docs/source/anomaly_detector.model.rst
  docs/source/anomaly_detector.rst
  docs/source/anomaly_detector.storage.rst
  docs/source/anomaly_detector.types.rst
  docs/source/api_reference.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/modules.rst
Labels: approved, size/L, size/S

#240 Adding better schema for storing facts for multiple services.
  anomaly_detector/fact_store/app.py
  anomaly_detector/fact_store/fact_store_api.py
  anomaly_detector/fact_store/model.py
  scripts/run-web-ui.sh
  tests/test_factstore.py
Labels: approved, size/L, size/M

#243 Adding tracking of human feedback
  anomaly_detector/fact_store/app.py
Labels: approved, size/S

#245 adding notebook k-means experiment
  Notebooks/experiment/LAD_Core_Minimal.ipynb
Labels: approved, model-inference, model-training, size/XXL

#244 Adding release scripts for images and pypi
  scripts/build-s2i-push-quay.sh
  scripts/release.sh
Labels: approved, size/S, size/XS

#246 Updating image of components
  imgs/components.png
Labels: approved, size/XS
